'use strict'
module.exports = {
  NODE_ENV: '"production"',

  FIREBASE_APIKEY: process.env.FIREBASE_APIKEY_PROD,
  FIREBASE_AUTHDOMAIN: process.env.FIREBASE_AUTHDOMAIN_PROD,
  FIREBASE_DATABASEURL: process.env.FIREBASE_DATABASEURL_PROD,
  FIREBASE_PROJECTID: process.env.FIREBASE_PROJECTID_PROD,
  FIREBASE_STORAGEBUCKET: process.env.FIREBASE_STORAGEBUCKET_PROD,
  FIREBASE_MESSAGINGSENDERID: process.env.FIREBASE_MESSAGINGSENDERID_PROD,
  FIREBASE_FUNCTIONSURL: process.env.FIREBASE_FUNCTIONSURL_PROD,
  GOOGLE_ANALYTICS_UA: process.env.GOOGLE_ANALYTICS_UA_PROD
}
