# Generated by Django 3.0.7 on 2020-06-28 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('website', models.URLField(verbose_name='website')),
                ('twitter', models.CharField(blank=True, max_length=254, null=True, verbose_name='twitter')),
                ('facebook', models.CharField(blank=True, max_length=254, null=True, verbose_name='facebook')),
                ('linkedin', models.CharField(blank=True, max_length=254, null=True, verbose_name='linkedin')),
                ('bio', models.TextField(verbose_name='bio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
